### ISSUE TITLE
Applying pretrained proglobal model on test file fails

### ISSUE THREAD

**Issue by aurghob** [allenai/propara#13]
Hi,

According to proglobal's readme,
I trained the model by running : 

> python propara/runProGlobal.py train tests/fixtures/proglobal_params.json -s /tmp/pgl/

and then tried applying the model on the test file by running:

> python propara/runProGlobalPredictor.py predict data/naacl/proglobal/proglobal.model.tar.gz data/naacl/proglobal/all.chain.test.v3.recurssive.json --output-file data/naacl/proglobal/output/test.prediction.txt

But I get the following error:

>  INFO - allennlp.nn.initializers -    _text_field_embedder.token_embedder_tokens_list.weight
> Traceback (most recent call last):
>   File "propara/runProGlobalPredictor.py", line 16, in <module>
>     main(prog="python -m allennlp.run")#, predictor_overrides=predictor_overrides)
>   File "/home/user/anaconda3/envs/propara/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 65, in main
>     args.func(args)
>   File "/home/user/anaconda3/envs/propara/lib/python3.6/site-packages/allennlp/commands/predict.py", line 137, in _predict
>     predictor = _get_predictor(args)
>   File "/home/user/anaconda3/envs/propara/lib/python3.6/site-packages/allennlp/commands/predict.py", line 95, in _get_predictor
>     return Predictor.from_archive(archive, args.predictor)
>   File "/home/user/anaconda3/envs/propara/lib/python3.6/site-packages/allennlp/service/predictors/predictor.py", line 111, in from_archive
>     raise ConfigurationError(f"No default predictor for model type {model_type}.\n"\
> allennlp.common.checks.ConfigurationError: 'No default predictor for model type ProGlobal.\nPlease specify a predictor explicitly.'

I tried instantiating a model through PretrainedModel but it did not seem to work.
Do let me know what I might be doing wrong here.

**Comment by aurghob** [comment]
Closing this issue as I was able to resolve this. The error was because the Readme does not specify a predictor name while running the predictor but we need to add the option. so: adding --predictor "ProGlobalPrediction" , does the trick

net predictor command to run:
python propara/runProGlobalPredictor.py predict data/naacl18/proglobal/proglobal.model.tar.gz data/naacl18/proglobal/all.chain.test.v3.recurssive.json --output-file data/naacl18/proglobal/output/test.prediction.txt --predictor "ProGlobalPrediction"
